jobs:
 - name: u14scala-test
   type: runSh
   steps:
     - IN: u14all-testing
     - TASK:
         runtime:
           options:
             imageName: "drydock/u14scaall"
             imageTag: master
         script:
           - /usr/local/scala-2.12.6/bin/scala -version
           - /usr/local/scala-2.11.12/bin/scala -version
